exports.userError = {
    emptyFirstName: "Veuillez entrer votre prénom",
    emptyLastName: "Veuillez entrer votre nom",
    emptyPhoneNumber: "Veuillez entrer votre numéro de téléphone",
    emptyEmail: "Veuillez entrer votre Email",
    emptyIdentityDocumentNumber: "Veuillez entrer votre numéro de document d'identité",
    emptyPassword: "Veuillez entrer votre mot de passe",
    emptyCity : "Veuillez entrer votre ville",
    emptyBirthDate : "Veuillez entrer votre date de naissance",
    email: "Veuilez entrer une adress e-mail correcte",
    isAuth: "Accès refusé",
    isUser: "Admin Resource, Accès refusé !",
    checkThisEmailIfAlreadyExist: "cette email déjà exist",
    passwordAndConfirmPasswordIsMatch: "Les mots de passe saisis ne sont pas identiques.",
    checkThisEmailIfNotExist: "Ce compte n'existe pas ! Veuillez-vous inscrire",
    invalidUserPassword: "Veuillez entrer un mot de passe correct",
    disconnected: "Vous êtes déconnecté",
    validCurrentPassword: "Le mot de passe actuel saisi est incorrect",
    updatedPassword: "le mot de pass a été modifiée",
    invalidCert: "Invalid private cert",
    Unauthorized: "Non autorisé",
    Disconnected: "Disconnected"
}
